# Generated by Django 4.0.3 on 2022-05-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=70)),
                ('lname', models.TextField(max_length=70)),
                ('uname', models.TextField(max_length=70)),
                ('email_name', models.EmailField(max_length=254)),
                ('pass1', models.TextField(max_length=70)),
                ('add', models.TextField(max_length=70)),
            ],
        ),
    ]
