# Generated by Django 4.0.3 on 2022-05-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_page', '0002_signup_detail_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_detail',
            name='img_name',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
