# Generated by Django 4.0.4 on 2022-05-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_page', '0004_remove_signup_detail_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_detail',
            name='img_name',
            field=models.ImageField(upload_to='upload_img'),
        ),
    ]
