# Generated by Django 4.0.4 on 2022-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_page', '0012_alter_signup_detail_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_detail',
            name='img_name',
            field=models.ImageField(upload_to='upload_img'),
        ),
    ]
