# Generated by Django 4.0.4 on 2022-05-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_page', '0013_alter_signup_detail_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_detail',
            name='img_name',
            field=models.FileField(upload_to='upload_adesh_files'),
        ),
    ]
